//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace studenrecordsystem.SearchWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        private System.DateTime BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GsmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIdField, value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Gsm {
            get {
                return this.GsmField;
            }
            set {
                if ((object.ReferenceEquals(this.GsmField, value) != true)) {
                    this.GsmField = value;
                    this.RaisePropertyChanged("Gsm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Adress", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Adress : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int StudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NeighborhoodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((this.StudentIdField.Equals(value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Neighborhood {
            get {
                return this.NeighborhoodField;
            }
            set {
                if ((object.ReferenceEquals(this.NeighborhoodField, value) != true)) {
                    this.NeighborhoodField = value;
                    this.RaisePropertyChanged("Neighborhood");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SearchWebService.SearhWebServiceSoap")]
    public interface SearhWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name StudentIdToFindStudent from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRecord", ReplyAction="*")]
        studenrecordsystem.SearchWebService.FindRecordResponse FindRecord(studenrecordsystem.SearchWebService.FindRecordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindRecord", ReplyAction="*")]
        System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.FindRecordResponse> FindRecordAsync(studenrecordsystem.SearchWebService.FindRecordRequest request);
        
        // CODEGEN: Generating message contract since element name StudentIdToPrint from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudent", ReplyAction="*")]
        studenrecordsystem.SearchWebService.GetStudentResponse GetStudent(studenrecordsystem.SearchWebService.GetStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudent", ReplyAction="*")]
        System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.GetStudentResponse> GetStudentAsync(studenrecordsystem.SearchWebService.GetStudentRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HowManyAdress", ReplyAction="*")]
        studenrecordsystem.SearchWebService.HowManyAdressResponse HowManyAdress(studenrecordsystem.SearchWebService.HowManyAdressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HowManyAdress", ReplyAction="*")]
        System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.HowManyAdressResponse> HowManyAdressAsync(studenrecordsystem.SearchWebService.HowManyAdressRequest request);
        
        // CODEGEN: Generating message contract since element name StudentIdToPrint from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAdress", ReplyAction="*")]
        studenrecordsystem.SearchWebService.GetAdressResponse GetAdress(studenrecordsystem.SearchWebService.GetAdressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAdress", ReplyAction="*")]
        System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.GetAdressResponse> GetAdressAsync(studenrecordsystem.SearchWebService.GetAdressRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRecordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindRecord", Namespace="http://tempuri.org/", Order=0)]
        public studenrecordsystem.SearchWebService.FindRecordRequestBody Body;
        
        public FindRecordRequest() {
        }
        
        public FindRecordRequest(studenrecordsystem.SearchWebService.FindRecordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindRecordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentIdToFindStudent;
        
        public FindRecordRequestBody() {
        }
        
        public FindRecordRequestBody(string StudentIdToFindStudent) {
            this.StudentIdToFindStudent = StudentIdToFindStudent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindRecordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindRecordResponse", Namespace="http://tempuri.org/", Order=0)]
        public studenrecordsystem.SearchWebService.FindRecordResponseBody Body;
        
        public FindRecordResponse() {
        }
        
        public FindRecordResponse(studenrecordsystem.SearchWebService.FindRecordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindRecordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int FindRecordResult;
        
        public FindRecordResponseBody() {
        }
        
        public FindRecordResponseBody(int FindRecordResult) {
            this.FindRecordResult = FindRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudent", Namespace="http://tempuri.org/", Order=0)]
        public studenrecordsystem.SearchWebService.GetStudentRequestBody Body;
        
        public GetStudentRequest() {
        }
        
        public GetStudentRequest(studenrecordsystem.SearchWebService.GetStudentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentIdToPrint;
        
        public GetStudentRequestBody() {
        }
        
        public GetStudentRequestBody(string StudentIdToPrint) {
            this.StudentIdToPrint = StudentIdToPrint;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentResponse", Namespace="http://tempuri.org/", Order=0)]
        public studenrecordsystem.SearchWebService.GetStudentResponseBody Body;
        
        public GetStudentResponse() {
        }
        
        public GetStudentResponse(studenrecordsystem.SearchWebService.GetStudentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public studenrecordsystem.SearchWebService.Student GetStudentResult;
        
        public GetStudentResponseBody() {
        }
        
        public GetStudentResponseBody(studenrecordsystem.SearchWebService.Student GetStudentResult) {
            this.GetStudentResult = GetStudentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowManyAdressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowManyAdress", Namespace="http://tempuri.org/", Order=0)]
        public studenrecordsystem.SearchWebService.HowManyAdressRequestBody Body;
        
        public HowManyAdressRequest() {
        }
        
        public HowManyAdressRequest(studenrecordsystem.SearchWebService.HowManyAdressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HowManyAdressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public HowManyAdressRequestBody() {
        }
        
        public HowManyAdressRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HowManyAdressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HowManyAdressResponse", Namespace="http://tempuri.org/", Order=0)]
        public studenrecordsystem.SearchWebService.HowManyAdressResponseBody Body;
        
        public HowManyAdressResponse() {
        }
        
        public HowManyAdressResponse(studenrecordsystem.SearchWebService.HowManyAdressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HowManyAdressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int HowManyAdressResult;
        
        public HowManyAdressResponseBody() {
        }
        
        public HowManyAdressResponseBody(int HowManyAdressResult) {
            this.HowManyAdressResult = HowManyAdressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdress", Namespace="http://tempuri.org/", Order=0)]
        public studenrecordsystem.SearchWebService.GetAdressRequestBody Body;
        
        public GetAdressRequest() {
        }
        
        public GetAdressRequest(studenrecordsystem.SearchWebService.GetAdressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAdressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StudentIdToPrint;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int adressNo;
        
        public GetAdressRequestBody() {
        }
        
        public GetAdressRequestBody(string StudentIdToPrint, int adressNo) {
            this.StudentIdToPrint = StudentIdToPrint;
            this.adressNo = adressNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdressResponse", Namespace="http://tempuri.org/", Order=0)]
        public studenrecordsystem.SearchWebService.GetAdressResponseBody Body;
        
        public GetAdressResponse() {
        }
        
        public GetAdressResponse(studenrecordsystem.SearchWebService.GetAdressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAdressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public studenrecordsystem.SearchWebService.Adress GetAdressResult;
        
        public GetAdressResponseBody() {
        }
        
        public GetAdressResponseBody(studenrecordsystem.SearchWebService.Adress GetAdressResult) {
            this.GetAdressResult = GetAdressResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearhWebServiceSoapChannel : studenrecordsystem.SearchWebService.SearhWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearhWebServiceSoapClient : System.ServiceModel.ClientBase<studenrecordsystem.SearchWebService.SearhWebServiceSoap>, studenrecordsystem.SearchWebService.SearhWebServiceSoap {
        
        public SearhWebServiceSoapClient() {
        }
        
        public SearhWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearhWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearhWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearhWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        studenrecordsystem.SearchWebService.FindRecordResponse studenrecordsystem.SearchWebService.SearhWebServiceSoap.FindRecord(studenrecordsystem.SearchWebService.FindRecordRequest request) {
            return base.Channel.FindRecord(request);
        }
        
        public int FindRecord(string StudentIdToFindStudent) {
            studenrecordsystem.SearchWebService.FindRecordRequest inValue = new studenrecordsystem.SearchWebService.FindRecordRequest();
            inValue.Body = new studenrecordsystem.SearchWebService.FindRecordRequestBody();
            inValue.Body.StudentIdToFindStudent = StudentIdToFindStudent;
            studenrecordsystem.SearchWebService.FindRecordResponse retVal = ((studenrecordsystem.SearchWebService.SearhWebServiceSoap)(this)).FindRecord(inValue);
            return retVal.Body.FindRecordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.FindRecordResponse> studenrecordsystem.SearchWebService.SearhWebServiceSoap.FindRecordAsync(studenrecordsystem.SearchWebService.FindRecordRequest request) {
            return base.Channel.FindRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.FindRecordResponse> FindRecordAsync(string StudentIdToFindStudent) {
            studenrecordsystem.SearchWebService.FindRecordRequest inValue = new studenrecordsystem.SearchWebService.FindRecordRequest();
            inValue.Body = new studenrecordsystem.SearchWebService.FindRecordRequestBody();
            inValue.Body.StudentIdToFindStudent = StudentIdToFindStudent;
            return ((studenrecordsystem.SearchWebService.SearhWebServiceSoap)(this)).FindRecordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        studenrecordsystem.SearchWebService.GetStudentResponse studenrecordsystem.SearchWebService.SearhWebServiceSoap.GetStudent(studenrecordsystem.SearchWebService.GetStudentRequest request) {
            return base.Channel.GetStudent(request);
        }
        
        public studenrecordsystem.SearchWebService.Student GetStudent(string StudentIdToPrint) {
            studenrecordsystem.SearchWebService.GetStudentRequest inValue = new studenrecordsystem.SearchWebService.GetStudentRequest();
            inValue.Body = new studenrecordsystem.SearchWebService.GetStudentRequestBody();
            inValue.Body.StudentIdToPrint = StudentIdToPrint;
            studenrecordsystem.SearchWebService.GetStudentResponse retVal = ((studenrecordsystem.SearchWebService.SearhWebServiceSoap)(this)).GetStudent(inValue);
            return retVal.Body.GetStudentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.GetStudentResponse> studenrecordsystem.SearchWebService.SearhWebServiceSoap.GetStudentAsync(studenrecordsystem.SearchWebService.GetStudentRequest request) {
            return base.Channel.GetStudentAsync(request);
        }
        
        public System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.GetStudentResponse> GetStudentAsync(string StudentIdToPrint) {
            studenrecordsystem.SearchWebService.GetStudentRequest inValue = new studenrecordsystem.SearchWebService.GetStudentRequest();
            inValue.Body = new studenrecordsystem.SearchWebService.GetStudentRequestBody();
            inValue.Body.StudentIdToPrint = StudentIdToPrint;
            return ((studenrecordsystem.SearchWebService.SearhWebServiceSoap)(this)).GetStudentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        studenrecordsystem.SearchWebService.HowManyAdressResponse studenrecordsystem.SearchWebService.SearhWebServiceSoap.HowManyAdress(studenrecordsystem.SearchWebService.HowManyAdressRequest request) {
            return base.Channel.HowManyAdress(request);
        }
        
        public int HowManyAdress(string id) {
            studenrecordsystem.SearchWebService.HowManyAdressRequest inValue = new studenrecordsystem.SearchWebService.HowManyAdressRequest();
            inValue.Body = new studenrecordsystem.SearchWebService.HowManyAdressRequestBody();
            inValue.Body.id = id;
            studenrecordsystem.SearchWebService.HowManyAdressResponse retVal = ((studenrecordsystem.SearchWebService.SearhWebServiceSoap)(this)).HowManyAdress(inValue);
            return retVal.Body.HowManyAdressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.HowManyAdressResponse> studenrecordsystem.SearchWebService.SearhWebServiceSoap.HowManyAdressAsync(studenrecordsystem.SearchWebService.HowManyAdressRequest request) {
            return base.Channel.HowManyAdressAsync(request);
        }
        
        public System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.HowManyAdressResponse> HowManyAdressAsync(string id) {
            studenrecordsystem.SearchWebService.HowManyAdressRequest inValue = new studenrecordsystem.SearchWebService.HowManyAdressRequest();
            inValue.Body = new studenrecordsystem.SearchWebService.HowManyAdressRequestBody();
            inValue.Body.id = id;
            return ((studenrecordsystem.SearchWebService.SearhWebServiceSoap)(this)).HowManyAdressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        studenrecordsystem.SearchWebService.GetAdressResponse studenrecordsystem.SearchWebService.SearhWebServiceSoap.GetAdress(studenrecordsystem.SearchWebService.GetAdressRequest request) {
            return base.Channel.GetAdress(request);
        }
        
        public studenrecordsystem.SearchWebService.Adress GetAdress(string StudentIdToPrint, int adressNo) {
            studenrecordsystem.SearchWebService.GetAdressRequest inValue = new studenrecordsystem.SearchWebService.GetAdressRequest();
            inValue.Body = new studenrecordsystem.SearchWebService.GetAdressRequestBody();
            inValue.Body.StudentIdToPrint = StudentIdToPrint;
            inValue.Body.adressNo = adressNo;
            studenrecordsystem.SearchWebService.GetAdressResponse retVal = ((studenrecordsystem.SearchWebService.SearhWebServiceSoap)(this)).GetAdress(inValue);
            return retVal.Body.GetAdressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.GetAdressResponse> studenrecordsystem.SearchWebService.SearhWebServiceSoap.GetAdressAsync(studenrecordsystem.SearchWebService.GetAdressRequest request) {
            return base.Channel.GetAdressAsync(request);
        }
        
        public System.Threading.Tasks.Task<studenrecordsystem.SearchWebService.GetAdressResponse> GetAdressAsync(string StudentIdToPrint, int adressNo) {
            studenrecordsystem.SearchWebService.GetAdressRequest inValue = new studenrecordsystem.SearchWebService.GetAdressRequest();
            inValue.Body = new studenrecordsystem.SearchWebService.GetAdressRequestBody();
            inValue.Body.StudentIdToPrint = StudentIdToPrint;
            inValue.Body.adressNo = adressNo;
            return ((studenrecordsystem.SearchWebService.SearhWebServiceSoap)(this)).GetAdressAsync(inValue);
        }
    }
}
